const mockFollowers =[
  {
  "login": "RobertHJones",
  "id": 80783254,
  "node_id": "MDQ6VXNlcjgwNzgzMjU0",
  "avatar_url": "https://avatars.githubusercontent.com/u/80783254?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/RobertHJones",
  "html_url": "https://github.com/RobertHJones",
  "followers_url": "https://api.github.com/users/RobertHJones/followers",
  "following_url": "https://api.github.com/users/RobertHJones/following{/other_user}",
  "gists_url": "https://api.github.com/users/RobertHJones/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/RobertHJones/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/RobertHJones/subscriptions",
  "organizations_url": "https://api.github.com/users/RobertHJones/orgs",
  "repos_url": "https://api.github.com/users/RobertHJones/repos",
  "events_url": "https://api.github.com/users/RobertHJones/events{/privacy}",
  "received_events_url": "https://api.github.com/users/RobertHJones/received_events",
  "type": "User",
  "site_admin": false
  },
  {
  "login": "cazmaar",
  "id": 88379572,
  "node_id": "MDQ6VXNlcjg4Mzc5NTcy",
  "avatar_url": "https://avatars.githubusercontent.com/u/88379572?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/cazmaar",
  "html_url": "https://github.com/cazmaar",
  "followers_url": "https://api.github.com/users/cazmaar/followers",
  "following_url": "https://api.github.com/users/cazmaar/following{/other_user}",
  "gists_url": "https://api.github.com/users/cazmaar/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/cazmaar/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/cazmaar/subscriptions",
  "organizations_url": "https://api.github.com/users/cazmaar/orgs",
  "repos_url": "https://api.github.com/users/cazmaar/repos",
  "events_url": "https://api.github.com/users/cazmaar/events{/privacy}",
  "received_events_url": "https://api.github.com/users/cazmaar/received_events",
  "type": "User",
  "site_admin": false
  },
  {
  "login": "ojxade312",
  "id": 90218679,
  "node_id": "MDQ6VXNlcjkwMjE4Njc5",
  "avatar_url": "https://avatars.githubusercontent.com/u/90218679?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/ojxade312",
  "html_url": "https://github.com/ojxade312",
  "followers_url": "https://api.github.com/users/ojxade312/followers",
  "following_url": "https://api.github.com/users/ojxade312/following{/other_user}",
  "gists_url": "https://api.github.com/users/ojxade312/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/ojxade312/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/ojxade312/subscriptions",
  "organizations_url": "https://api.github.com/users/ojxade312/orgs",
  "repos_url": "https://api.github.com/users/ojxade312/repos",
  "events_url": "https://api.github.com/users/ojxade312/events{/privacy}",
  "received_events_url": "https://api.github.com/users/ojxade312/received_events",
  "type": "User",
  "site_admin": false
  }
  ]
export default mockFollowers;
