const mockUser= {
  "login": "Ilie1985",
  "id": 93831437,
  "node_id": "U_kgDOBZfBDQ",
  "avatar_url": "https://avatars.githubusercontent.com/u/93831437?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Ilie1985",
  "html_url": "https://github.com/Ilie1985",
  "followers_url": "https://api.github.com/users/Ilie1985/followers",
  "following_url": "https://api.github.com/users/Ilie1985/following{/other_user}",
  "gists_url": "https://api.github.com/users/Ilie1985/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Ilie1985/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Ilie1985/subscriptions",
  "organizations_url": "https://api.github.com/users/Ilie1985/orgs",
  "repos_url": "https://api.github.com/users/Ilie1985/repos",
  "events_url": "https://api.github.com/users/Ilie1985/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Ilie1985/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Marian Ilie",
  "company": null,
  "blog": "",
  "location": "London ,United Kingdom",
  "email": null,
  "hireable": null,
  "bio": "Hello! My name is Marian Ilie.\r\nI am a front-end web-developer and web designer .",
  "twitter_username": null,
  "public_repos": 59,
  "public_gists": 0,
  "followers": 3,
  "following": 3,
  "created_at": "2021-11-06T15:09:01Z",
  "updated_at": "2022-12-22T11:04:25Z"
  }
export default mockUser